name: PiRadar Agent Runtime v3.1

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # heartbeat každých 10 minut

permissions:
  contents: write

env:
  AGENT_MANIFEST_PATH: manifest/piradar_core_agent_v3.0.xml

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate XML manifest
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y python3 jq curl
          python3 - <<'PY'
          import xml.etree.ElementTree as ET
          path = "manifest/piradar_core_agent_v3.0.xml"
          tree = ET.parse(path)
          root = tree.getroot()
          if root.tag != "agent":
              raise SystemExit("Manifest syntax error: Root tag must be <agent>")
          print("Manifest syntax OK")
          PY

      - name: Fetch Bitget data (robust)
        run: |
          set -euo pipefail
          mkdir -p out public/feed
          curl -fsS https://api.bitget.com/api/spot/v1/market/tickers -o out/raw.json || true
          if [ -s out/raw.json ]; then
            jq -e '{
              timestamp: (now | todate),
              data: ((.data // []) | map(select(.symbol=="BTCUSDT" or .symbol=="ETHUSDT" or .symbol=="SOLUSDT" or .symbol=="PIUSDT")))
            }' out/raw.json > out/priceSnapshot.json
          else
            printf '{"timestamp":"%s","warning":"bitget_unreachable","data":[]}' \
                   "$(date -u +"%Y-%m-%dT%H:%M:%SZ")" > out/priceSnapshot.json
          fi
          cp out/priceSnapshot.json public/feed/now.json
          echo "Saved snapshot → out/priceSnapshot.json & public/feed/now.json"

      - name: Commit & push snapshot (only if changed)
        run: |
          set -euo pipefail
          git config user.name  "PiRadar Agent"
          git config user.email "agent@piradar.local"
          git add out/priceSnapshot.json public/feed/now.json || true
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update: Bitget snapshot [skip ci]"
            git push
            echo "Snapshot committed & pushed."
          else
            echo "No changes to commit."
          fi

